config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root :to => 'homes#top'
	get 'home/about' => 'homes#about', as: :about

    resources :users
	resources :books

	# devise_for :users, controllers: {
	#   sessions: 'users/sessions',
	#   registrations: 'users/registrations'
	# }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
  def after_sign_in_path_for(resource)
    user_path(current_user.id) # ログイン後に遷移するpathを設定
  end
  def after_sign_out_path_for(resouece)
    flash[:notice] = "Signed out successfully."
    root_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
  def index
    @book = Book.new
  	@books = Book.all
    @users = User.all
    @user = current_user
  end

  def show
  	@book = Book.find(params[:id])
  end

  def new
  end

  def edit
  	@book = Book.find(params[:id])
    @user = current_user
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def create
  	@book = Book.new(book_params)
    @user = current_user
    @books = Book.all
  	@book.user_id = current_user.id
    if @book.save
    	flash[:notice] = "You have creatad book successfully."
    	redirect_to book_path(@book)
    else
    	render "index"
    end
  end
  def destroy
  	book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
          flash[:notice] = "You have updated book successfully."
          redirect_to book_path(@book)
        else
          render "edit"
        end

  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end

	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

	def index
	   @book = Book.new
	   @users = User.all
	   @user = current_user
	end

	def show
		@user = User.find(params[:id])
		@book = Book.new
		@books = @user.books
	end

	def edit
		@user = User.find(params[:id])
        if @user.id != current_user.id
           redirect_to user_path(current_user)
        end
	end

	def destroy
		book = Book.find(params[:id])
	end

	def create
    user.save
    redirect_to users_path
	end

	def update
		@user = User.find(params[:id])
        if @user.update(user_params)
       	flash[:notice] = "You have updated user successfully."
        redirect_to user_path(@user.id)
        else
        render "edit"
    end
	end



	private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<h2>User info</h2>
     <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size:'100x100' %>
    <table class="table">

      <tbody>
      	<tr></tr> 
      <tr>
    	  <th>name</th>
    	  <th><%= user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th><%= user.introduction %></th>
      </tr>
</tbody></table>

<div class="row">
  <%=link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
</div>


<h2>New book</h2>
<% if book.errors.any? %>
<p><%=book.errors.full_messages.length%> errors prohibited this obj from being saved:</p>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
    <%= form_for(book) do |f| %>
    <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: "col-xs-12" %>
    </div>
    <div class="field row">
    <%= f.label :body, "Opinion" %>
    <%= f.text_area :body, class: "col-xs-12" %>
    </div>
    <br>
    <div class="field row">
    <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
    </div>
    <% end %>

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>
<!-- form_for部分 -->
<% if @book.errors.any? %>
<p><%=@book.errors.full_messages.length%> errors prohibited this obj from being saved:</p>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for(@book) do |f| %>
<div class="field row">
  <%= f.label :title %>
  <%= f.text_field :title, class: "col-xs-12" %>
</div>
<div class="field row">
  <%= f.label :body, "Opinion" %>
  <%= f.text_area :body, class: "col-xs-12"%>
</div>
  <br>
  <div class="field row">
  <%= f.submit 'Update Book', class: "btn-sm btn-primary col-xs-12" %>
</div>

  <%=link_to "Show", book_path(@book) %><span>|</span>
  <%=link_to "Back", books_path %>


<% end %>
</div>

app/views/books/index.html.erb
<div class="container">
      <div class="row">
<div class="col-xs-3">

<%= render 'books/new', book: @book, user: @user %>
</div>

 <div class="col-xs-9">

<h2>Books</h2>
<table class="table table-hover table-inverse">
<thead>
  <tr>
  	<th></th>
    <th>Title</th><th>Opinion</th>
</tr>
</thead>
<tbody>
<% @books.each do |book| %>
<tr>

  <td>
  	<%= link_to user_path(book.id) do %>
  	<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
  	<% end %>
  </td>
  <td>
    <%= link_to book_path(book.id) do %>
  	<%= book.title %>
    <% end %>
  	</td>
  <td><%= book.body %></td>
  <th colspan="3"></th>

</tr>
<% end %>
</tbody>
</table>
</div>
</div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container">
      <div class="row">
<div class="col-xs-3">

<%= render 'books/new', book: Book.new, user: @book.user %>
</div>

<div class="col-xs-9">

	<h2> Book detail</h2>

<table class="table">
	<tbody>
		<tr>
          <td>
          	<%= link_to user_path(@book.user) do %>
  	        <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %><br>
            <%= @book.user.name %>
  	        <% end %>
          </td>
          <% if @book.user==current_user %>

            <td><%= link_to @book.title, book_path(@book.id) %></td>
            <td><%= @book.body %></td>
            <td><%=link_to "Edit", edit_book_path(@book.id), class: "btn-sm btn-success" %></td>
            <td><%=link_to "Destroy", book_path(@book.id), class: "btn-sm btn-danger", method: :delete, data: {confirm: "ほんとに消しますか？"} %></td>
            <% else %>
            <td><%= link_to @book.title, book_path(@book.id) %></td>
            <td><%= @book.body %></td>

            <% end %>


        </tr>
    </tbody>
</table>
</div>
</div>
</div>

app/views/homes/about.html.erb
<div class="container">

        <p id="notice"></p>


      	<h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>


      </div>

app/views/homes/top.html.erb
      <div class="container">

        <div class="row">
  <div class="top-message col-md-offset-3 col-md-6">
    <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
          <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about various books!</p>

    <div class="btn-wrapper">
      <div class="row">
         <p><%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %></p>
      </div>
      <div class="row">
        <p><%= link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %></p>
      </div>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left">

      <span class="header-title">Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>

          <li><%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home home" %></li>
          <li><%= link_to " Users", users_path, class: "glyphicon glyphicon-link about" %></li>
          <li><%= link_to " Books", books_path, class: "glyphicon glyphicon-edit sign_up" %></li>
          <li><%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-in sign_in" %></li>

        <% else %>

          <li><%= link_to " Home", root_path, class: "glyphicon glyphicon-home home" %></li>
          <li><%= link_to " About", about_path, class: "glyphicon glyphicon-link about" %></li>
          <li><%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
          <li><%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %></li>
          <% end %>
      </ul>
    </nav>
  </div>
</header>
<div class="container">
<p id="notice"><%= notice %></p>
    <%= yield %>
</div>
<footer>
  <div class="container">
    <div class="row">
      <div class="col-xs-3 col-xs-offset-9">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>
  </body>
</html>

app/views/users/edit.html.erb
<h2>User info</h2>

<% if @user.errors.any? %>
<p><%=@user.errors.full_messages.length%> errors prohibited this obj from being saved:</p>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@user) do |f| %>
    <div class="form-group has-icon">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>
        <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
    </div>

    <div class="form-group has-icon">
    <div class="user-edit-image">

    </div>
    <%= f.label :profile_image, "Image" %>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
</div>
<div class="field">
    <%= f.label :introduction %>
    <%=f.text_area :introduction %>
  </div>

    <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div class="container">
      <div class="row">
<div class="col-xs-3">

<%= render 'books/new', book: @book, user: @user %>
</div>

 <div class="col-xs-9">

<h2>Users</h2>

<table class="table">
 <thead>
  <tr>
  	<th>image</th>
    <th>name</th>
    <th colspan="3"></th>
</tr>
 </thead>
 <tbody>
<% @users.each do |user| %>

<tr>

  <td>
  <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
  </td>
  <td><%= user.name %></td>
  <td><%=link_to "Show", user_path(user.id) %></td>
  <th colspan="3"></th>

</tr>
<% end %>
</tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<html><head>
    <title>Bookers</title>
  </head>

  <body>

  	<div class="body">
      <div class="container">
      	<div class="row">
  <div class="col-xs-3">

    <%= render 'books/new', book: @book, user: @user %>
    
     </div>

  <div class="col-xs-9">
    <h2>Books</h2>

    <table class="table table-hover table-inverse">
      <thead>
    <tr> 
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
  <tr>
  <td><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %></td>
  <td>
    <%= link_to book_path(book.id) do %>
    <%= book.title %>
    <% end %>
  </td>
  <td><%= book.body %></td>
  <td>
  </td>
  </tr>
  <% end %>
  </tbody>
</table>

  </div>
</div>
      </div>
    </div>
</body></html>